all: fix build
Fix build for the latest akaros sources.
Tested with 6344ed04e307ba30df879d1d407b10a1b3236784 (Oct 5, 2017).

1. MAX_VCORES is not present in any akaros headers.
2. benchutil/alarm.h is moved to parlib/alarm.h.
3. SYS_gettimeofday does not exist anymore.
4. SYS_PIPE does not exist.
5. SYS_NANOSLEEP does exist now.

This now at least passes akaros.bash make,
and the resulting program actually started:

./testgo
Hello, Akaros!
fatal error: Exit Returned: We should never get here!

The exit crash is bad, but better than broken build.